<?php 
    if(Mage::getStoreConfig('news/news_general/enabled') == 1):
    ?>
    <?php $news =  $this->getNews(); ?>
    <?php  if(($news->getDateToUnpublish() >= date('Y-m-d 00:00:00')) && ($news->getDateToPublish()<date('Y-m-d 23:59:59'))){ ?>
        <div class="page-title"><h1><?php echo $news['title'];?></h1></div>
        <p><?php echo $news['news_content'];?></p>       
        <?php }else{ ?>
        <div><h4><?php echo $this->__('No News Found.'); ?></h4></div>
        <?php } ?>
    <?php 
        else:
        $url = Mage::getBaseUrl();
        Mage::app()->getFrontController()->getResponse()->setRedirect($url);
        endif;
?>