<footer class="container-fluid">
	<div class="footer-content container">
		<div class="row">
			<div class="col-md-4 col-xs-12">
				<address>
					<strong><?php echo Mage::getStoreConfig('general/store_information/name'); ?></strong>
					<ul class="list-unstyled">
						<li><?php echo Mage::getStoreConfig('general/store_information/address'); ?></li>
						<li><abbr title="Telephone number">T:</abbr> <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></li>
						<li><abbr title="Email address">E:</abbr> <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_general/email') ?>"><?php echo Mage::getStoreConfig('trans_email/ident_general/email'); ?></a></li>
					</ul>
				</address>
			</div>
			<div class="col-md-2 col-md-offset-4 col-xs-6">
				<strong>Links</strong>
				<ul class="list-unstyled">
					<li><a href="<?php echo $this->getUrl('') ?>">Home</a></li>
					<li><a href="<?php echo $this->getUrl('about') ?>">About</a></li>
					<li><a href="<?php echo $this->getUrl('services') ?>">Services</a></li>
					<li><a href="<?php echo $this->getUrl('products') ?>">Products</a></li>
					<li><a href="<?php echo $this->getUrl('faq') ?>">FAQ</a></li>
					<li><a href="<?php echo $this->getUrl('contact-us') ?>">Contact us</a></li>
				</ul>
			</div>
			<div class="col-md-2 col-xs-6">
				<strong>Social</strong>
				<ul class="list-unstyled">
					<?php if (Mage::getStoreConfig('skdev/social/facebook_field')): ?>
						<li><span class="entypo-social facebook"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/facebook_field'); ?>" target="_blank">Facebook</a></li>
					<?php endif; ?>
					<?php if (Mage::getStoreConfig('skdev/social/twitter_field')): ?>
						<li><span class="entypo-social twitter"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/twitter_field'); ?>" target="_blank">Twitter</a></li>
					<?php endif; ?>
					<?php if (Mage::getStoreConfig('skdev/social/instagram_field')): ?>
						<li><span class="entypo-social instagram"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/instagram_field'); ?>" target="_blank">Instagram</a></li>
					<?php endif; ?>
					<?php if (Mage::getStoreConfig('skdev/social/pinterest_field')): ?>
						<li><span class="entypo-social pinterest"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/pinterest_field'); ?>" target="_blank">Pinterest</a></li>
					<?php endif; ?>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<address><?php echo $this->getCopyright() ?></address>
			</div>
		</div>
	</div>
</footer>
