<footer class="container-fluid">
	<div class="footer-content container">
		<div class="row">
			<div class="col-md-4">
				<address>
					<h3><?php echo Mage::getStoreConfig('general/store_information/name'); ?></h3>
					<ul class="list-unstyled">
						<li><?php echo Mage::getStoreConfig('general/store_information/address'); ?></li>
						<li><span class="entypo phone"></span> <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></li>
						<li><span class="entypo mail"></span> <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_general/email') ?>"><?php echo Mage::getStoreConfig('trans_email/ident_general/email'); ?></a></li>
					</ul>
				</address>
			</div>
			<div class="col-md-2 col-md-offset-4">
				<h3>Links</h3>
				<ul class="list-unstyled">
					<li><a href="<?php echo $this->getUrl('') ?>">Home</a></li>
					<li><a href="<?php echo $this->getUrl('') ?>/about">About</a></li>
					<li><a href="<?php echo $this->getUrl('') ?>/services">Services</a></li>
					<li><a href="<?php echo $this->getUrl('') ?>/products">Products</a></li>
					<li><a href="<?php echo $this->getUrl('') ?>/faq">FAQ</a></li>
					<li><a href="<?php echo $this->getUrl('') ?>/contact-us">Contact us</a></li>
				</ul>
			</div>
			<div class="col-md-2">
				<h3>Social</h3>
				<ul class="list-unstyled">
					<?php if (Mage::getStoreConfig('skdev/social/facebook_field')): ?>
						<li><span class="entypo-social facebook"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/facebook_field'); ?>" target="_blank">Facebook</a></li>
					<?php endif; ?>
					<?php if (Mage::getStoreConfig('skdev/social/twitter_field')): ?>
						<li><span class="entypo-social twitter"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/twitter_field'); ?>">Twitter</a></li>
					<?php endif; ?>
					<?php if (Mage::getStoreConfig('skdev/social/instagram_field')): ?>
						<li><span class="entypo-social instagram"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/instagram_field'); ?>">Instagram</a></li>
					<?php endif; ?>
					<?php if (Mage::getStoreConfig('skdev/social/pinterest_field')): ?>
						<li><span class="entypo-social pinterest"></span> <a href="<?php echo Mage::getStoreConfig('skdev/social/pinterest_field'); ?>">Pinterest</a></li>
					<?php endif; ?>
				</ul>
			</div>
		</div>
		<div class="row">
			<div class="col-md-12">
				<address><?php echo $this->getCopyright() ?></address>
			</div>
		</div>
	</div>
</footer>

