<footer>
	<div class="container">
		<div class="footer-content">
			<div class="row">
				<div class="col-md-2 col-md-offset-8">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">About</a></li>
						<li><a href="#">Services</a></li>
						<li><a href="#">Products</a></li>
						<li><a href="#">FAQ</a></li>
						<li><a href="#">Contact us</a></li>
					</ul>
				</div>
				<div class="col-md-2">
					<ul>
						<li><a href="#">Facebook</a></li>
						<li><a href="#">Twitter</a></li>
						<li><a href="#">Instagram</a></li>
						<li><a href="#">Pinterest</a></li>
						<li><?php echo Mage::getStoreConfig('general/store_information/phone'); ?></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
    				<address><?php echo $this->getCopyright() ?></address>
				</div>
			</div>
		</div>
	</div>
</footer>

<?php var_dump(Mage::getStoreConfig('general/store_information')); ?>
