<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>

<div class="header-container">
    <div id="header-top">
        <div class="container">
            <?php echo $this->getChildHtml('topLinks') ?>
            <?php echo $this->getChildHtml('store_language') ?>
        </div>
    </div>
    <div id="header-middle">
        <div class="container">
            <?php if ($this->getIsHomePage()):?>
                <h1 class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
            <?php else:?>
                <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
            <?php endif?>

            <?php echo $this->getChildHtml('topContainer'); ?>
        </div>
    </div>
    <div id="header-bottom">
        <div class="container">
            <?php echo $this->getChildHtml('topMenu') ?>
        </div>
    </div>

</div><!-- .header-container -->