<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>

<div class="page-header">
    <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
    <p class="lead">If you have any question or comments, or if you would like to contact me for quote, please use the form below and we will get back to you as sooon as possible.</p>
</div>

<div class="row">
    <div class="col-md-6 col-md-push-6 col-xs-12 ">
        <address>
            <strong><?php echo Mage::getStoreConfig('general/store_information/name'); ?></strong>
            <ul class="list-unstyled">
                <li><?php echo Mage::getStoreConfig('general/store_information/address'); ?></li>
                <li><span class="entypo phone"></span> <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></li>
                <li><span class="entypo mail"></span> <a href="mailto:<?php echo Mage::getStoreConfig('trans_email/ident_general/email') ?>"><?php echo Mage::getStoreConfig('trans_email/ident_general/email'); ?></a></li>
            </ul>
        </address>        
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-xs-12">
        <form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post" role="form" class="form-horizontal">
            <div class="fieldset">
                <!-- Name -->
                <div class="form-group">
                    <label for="name" class="required col-sm-2 control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Name') ?></label>
                    <div class="col-sm-6">
                        <input name="name" id="name" title="<?php echo Mage::helper('contacts')->__('Name') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry form-control" type="text" />
                    </div>
                </div>
                <!-- Email address -->
                <div class="form-group">
                    <label for="email" class="required col-sm-2 control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Email') ?></label>
                    <div class="col-sm-6">
                        <input name="email" id="email" title="<?php echo Mage::helper('contacts')->__('Email') ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email form-control" type="text" />
                    </div>
                </div>
                <!-- Telephone -->
                <div class="form-group">
                    <label for="telephone" class="col-sm-2 control-label"><?php echo Mage::helper('contacts')->__('Telephone') ?></label>
                    <div class="col-sm-6">
                        <input name="telephone" id="telephone" title="<?php echo Mage::helper('contacts')->__('Telephone') ?>" value="" class="input-text form-control" type="text" />
                    </div>
                </div>
                <!-- Comment -->
                <div class="form-group">
                    <label for="comment" class="required col-sm-2 control-label"><em>*</em><?php echo Mage::helper('contacts')->__('Comment') ?></label>
                    <div class="col-sm-8">
                        <textarea name="comment" id="comment" title="<?php echo Mage::helper('contacts')->__('Comment') ?>" class="required-entry input-text form-control" rows="5"></textarea>
                    </div>
                </div>
                <!-- Buttons -->
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <p><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                        <button type="submit" title="<?php echo Mage::helper('contacts')->__('Submit') ?>" class="btn btn-success"><span class="glyphicon glyphicon-send"></span>  <?php echo Mage::helper('contacts')->__('Submit') ?></button>
                    </div>
                </div>
            </div>
        </form>

        <script type="text/javascript">
        //<![CDATA[
            var contactForm = new VarienForm('contactForm', true);
        //]]>
        </script>        
    </div>
    
    <div class="col-md-6 col-xs-12">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('google_map')->toHtml(); ?> 
    </div>
</div>
