<?php $_links = $this->getLinks(); ?>

<?php if(count($_links)>0): ?>
	<div class="row">
		<div class="col-md-6 hidden-xs">
			<ul class="list-inline">
				<li><mark><span class="glyphicon glyphicon-earphone"></span> <?php echo Mage::getStoreConfig('general/store_information/phone'); ?></mark></li>
				<li><mark><span class="glyphicon glyphicon-envelope"></span> <?php echo Mage::getStoreConfig('trans_email/ident_general/email'); ?></mark></li>
			</ul>	
		</div>
		<div class="col-md-6 col-xs-12">
			<ul class="pull-right list-inline"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>
			    <?php foreach($_links as $_link): ?>
			        <?php if ($_link instanceof Mage_Core_Block_Abstract):?>
			            <?php echo $_link->toHtml() ?>
			        <?php else: ?>
			            <li<?php if($_link->getIsFirst()||$_link->getIsLast()): ?> class="<?php if($_link->getIsFirst()): ?>first<?php endif; ?><?php if($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?></li>
			        <?php endif;?>
			    <?php endforeach; ?>
			</ul>
		</div>
	</div>
<?php endif; ?>
