<?php  foreach ($types as $type) {
            if ( $messages = $this->getMessages($type) ) {
                if ( !$html ) {
                    $html .= '<ul class="list-unstyled">';
                }
                $html .= '<li><div class="alert alert-' . $type . '" role="alert">';
                $html .= '<ul class="list-unstyled">';

                foreach ( $messages as $message ) {
                    $html.= '<li>';
                    $html.= $message->getText();
                    $html.= '</li>';
                }
                $html .= '</ul>';
                $html .= '</div></li>';
            }
        }
        if ( $html) {
            $html .= '</ul>';
        }
?>
