<?php
/**
 * NeoTheme Austrlia (Neo Industries Pty Ltd)
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to Neo Industries Pty LTD Non-Distributable Software Modification License (NDSML)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.neotheme.com.au/legal/licenses/NDSM.html
 * If the license is not included with the package or for any other reason,
 * you did not receive your licence please send an email to
 * license@neotheme.com.au so we can send you a copy immediately.
 *
 * This software comes with no warrenty of any kind. By Using this software, the user agrees to hold
 * Neo Industries Pty Ltd harmless of any damage it may cause.
 *
 * @category    modules
 * @module      NeoTheme_ImageRotator
 * @copyright   Copyright (c) 2011 Neo Industries Pty Ltd (http://www.neotheme.com.au)
 * @license     http://www.neotheme.com.au/  Non-Distributable Software Modification License(NDSML 1.0)
 */
/**
 * @see NeoTheme_Blog_Block_Post_Summary
 */
 $formatType = Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_FORMAT_TYPE);
 $format = ($formatType != 'custom')?
    Mage::app()->getLocale()->getDateTimeFormat($formatType):
    Mage::getStoreConfig(NeoTheme_Blog_Helper_Data::XPATH_CONFIG_DATETIME_CUSTOM_FORMAT);
?>

<article class="post">
    <div class="page-title post-title"><h2><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>"><?php echo $this->getPost()->getTitle(); ?></a></h2></div>

    <ul class="post-metadata">
        <li class="post-time">
            <small>
                <?php echo $this->__('Posted On: ');?>
                <?php $date = ($this->getPost()->getPostDate() != NULL)? $this->getPost()->getPostDate()  : $this->getPost()->getCreatedAt() ; ?>
                <?php  echo Mage::app()->getLocale()->date($date)->toString($format); ?>
            </small>
        </li>
        <?php if ($authorName = $this->getPost()->getAuthor()) :?>
            <li class="post-author"><small><?php echo $this->__('by'); ?> <?php echo $authorName; ?></small></li>
        <?php endif;?>
    </ul>

    <div class="post-summary">
		<?php echo $this->getPost()->getSummary(); ?>
        <div class="read-more"><a href="<?php echo $this->getPost()->getReadMoreUrl(); ?>" class="btn btn-success">Read more</a></div>
    </div>

    <div class="post-info">
	    <?php if ( (int) $this->getPost()->getStatus() == NeoTheme_Blog_Model_Post::STATUS_DRAFT) : ?>
        	<h3 style="color:red;"><?php echo $this->__('[Draft] (not visible publicly)');?></h3>
        <?php endif; ?>
    </div>
</article>
