<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" class="no-js"> <!--<![endif]-->
<head>
	<?php echo $this->getChildHtml('head'); ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
	<?php echo $this->getChildHtml('after_body_start'); ?>
	<?php echo $this->getChildHtml('global_notices'); ?>

	<?php echo $this->getChildHtml('header'); ?>

	<div class="container-fluid">
		<div class="main" id="homepage">
			<!-- Content -->
			<?php echo $this->getChildHtml('content'); ?>
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<div class="divider"></div>
					</div>
				</div>
				<!-- Categories -->
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<div class="block">
							<div class="block-title">
								<strong><span class="glyphicon glyphicon-th-large"></span> Our product categories</strong>
							</div>
						</div>
						<div id="categories">
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('services') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/metal_polishing.png'); ?>" alt="Metal Polishing"></a>
										<h3><a href="<?php echo $this->getUrl('services') ?>" title="Radrestore Services">Services</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/cast-iron-radiators') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/cast_iron_radiators.png'); ?>" alt="Cast Iron Radiators"></a>
										<h3><a href="<?php echo $this->getUrl('products/cast-iron-radiators') ?>" title="Cast Iron Radiators">Cast Iron Radiators</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/radiator-valves') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/valves.png'); ?>" alt="Radiator Valves"></a>
										<h3><a href="<?php echo $this->getUrl('products/radiator-valves') ?>" title="Radiator Valves">Radiator Valves</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/shrouds-base-plates') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/shrouds.png'); ?>" alt="Shrouds &amp; Base Plates"></a>
										<h3><a href="<?php echo $this->getUrl('products/shrouds-base-plates') ?>" title="Shrouds &amp; Base Plates">Shrouds &amp; Base Plates</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/products/wall-stays') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/wall-stay.png'); ?>" alt="Wall Stays"></a>
										<h3><a href="<?php echo $this->getUrl('products/products/wall-stays') ?>" title="Wall Stays">Wall Stays</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/products/accessories') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/accessories.png'); ?>" alt="Accessories"></a>
										<h3><a href="<?php echo $this->getUrl('products/products/accessories') ?>" title="Accessories">Accessories</a></h3>
									</figcaption>
								</figure>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<!-- Twitter  -->
					<div class="col-md-12 col-sm-12">
						<a class="twitter-timeline" href="https://twitter.com/Radrestore1" data-widget-id="594848136671186944" data-chrome="nofooter noborders noscrollbar transparent">>Tweets by @Radrestore1</a>
						<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
					</div>					
				</div>

				<!-- Tweets 
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<?php echo $this->getChildHtml('tweets.tweets') ?>
					</div>
				</div>
				-->
			</div>
		</div>
	</div>

	<?php echo $this->getChildHtml('footer'); ?>

	<?php echo $this->getChildHtml('site.bottom.css.js'); ?>
	<?php echo $this->getChildHtml('before_body_end'); ?>
	<?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>