<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="<?php echo $this->getLang(); ?>" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<?php echo $this->getLang(); ?>" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<?php echo $this->getLang(); ?>" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<?php echo $this->getLang(); ?>" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<?php echo $this->getLang(); ?>" class="no-js"> <!--<![endif]-->
<head>
	<?php echo $this->getChildHtml('head'); ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
	<?php echo $this->getChildHtml('after_body_start'); ?>
	<?php echo $this->getChildHtml('global_notices'); ?>

	<?php echo $this->getChildHtml('header'); ?>

	<div class="container-fluid">
		<div class="main" id="homepage">
			<!-- Content -->
			<?php echo $this->getChildHtml('content'); ?>
			<div class="container">
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<div class="divider"></div>
					</div>
				</div>
				<!-- Diagram -->
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<div class="cd-product cd-container">
						    <div class="cd-product-wrapper">
						        <img src="<?php echo $this->getSkinUrl('images/photos/4-column-matt-black-front-white-background.jpg'); ?>" alt="4 Column in Matt Black">
						        <!-- image of our product -->
						        <ul>
						            <li class="cd-single-point">
										<a class="cd-img-replace" href="#0">More</a>
						                <div class="cd-more-info cd-top">
						                    <!-- 4 classes available: cd-top, cd-bottom, cd-left, cd-right -->
						                    <h2>Joint and seals</h2>
						                    <p>Every section of a cast iron radiator has a nipple and a seal. A nipple pictured 1 is generally made from either cast iron or steel. a cast iron radiator nipple has opposing threads, left and right. The opposing threads pull each section of radiator together using specially made tools. A seal or gasket pictured 2 is added before tightening. A gasket seals each section of radiator together, so not to leak. Every section of cast iron a radiator has two nipples and two gaskets!</p>	<a href="#0" class="cd-close-info cd-img-replace">Close</a>
						                </div>
						            </li>
						            <!-- .cd-single-point -->
						            <!-- other points of interest here -->
						        </ul>
						    </div>
						    <!-- .cd-product-wrapper -->
						</div>
						<!-- .cd-product -->
					</div>
				</div>
				<!-- Boxes -->
				<div class="row">
					<!-- Box 1 -->
					<div class="col-md-4 col-sm-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">Radiator restoration</h3>
							</div>
							<div class="panel-body">
								<p>Radiator restoration includes removing old fittings with new modern ones, removing old paint, testing for leaks, flushing the radiator from old debris and priming in black, grey or white. Priced at £189. <a href="<?php echo $this->getUrl('services/renovation') ?>">Read more</a></p>
							</div>
						</div>
					</div>
					<!-- Box 2 -->
					<div class="col-md-4 col-sm-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">Seal or joint replacement</h3>
							</div>
							<div class="panel-body">
								<p>What happens If the radiator has a leaking joint, seal, break in the cast or a pin hole during testing.? Seals can be repaired at £50, sections (if in stock) can be replaced for £70. <a href="<?php echo $this->getUrl('products/accessories') ?>">Read more</a></p>
							</div>
						</div>
					</div>
					<!-- Box 3 -->
					<div class="col-md-4 col-sm-12">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h3 class="panel-title">Full restoration</h3>
							</div>
							<div class="panel-body">
								<p>Full restoration includes every joint and seal to be replaced as well as all included in the standard restoration. 5 year guarantee applies. Priced at £350. <a href="<?php echo $this->getUrl('services/renovation') ?>">Read more</a></p>
								<p>If you require the radiators painted in a colour of your choice as well as primed there is a £40 charge. <a href="<?php echo $this->getUrl('products/radiator-finishes') ?>">Read more</a></p>
								<p>Any radiator over 1.2 meters has an additional cost of £40.</p>
							</div>
						</div>
					</div>
				</div>
				<!-- Categories -->
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<div class="block">
							<div class="block-title">
								<strong><span class="glyphicon glyphicon-th-large"></span> Our product categories</strong>
							</div>
						</div>
						<div id="categories">
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('services') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/metal_polishing.png'); ?>" alt="Metal Polishing"></a>
										<h3><a href="<?php echo $this->getUrl('services') ?>" title="Radrestore Services">Services</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/cast-iron-radiators') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/cast_iron_radiators.png'); ?>" alt="Cast Iron Radiators"></a>
										<h3><a href="<?php echo $this->getUrl('products/cast-iron-radiators') ?>" title="Cast Iron Radiators">Cast Iron Radiators</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/radiator-valves') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/valves.png'); ?>" alt="Radiator Valves"></a>
										<h3><a href="<?php echo $this->getUrl('products/radiator-valves') ?>" title="Radiator Valves">Radiator Valves</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/shrouds-base-plates') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/shrouds.png'); ?>" alt="Shrouds &amp; Base Plates"></a>
										<h3><a href="<?php echo $this->getUrl('products/shrouds-base-plates') ?>" title="Shrouds &amp; Base Plates">Shrouds &amp; Base Plates</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/products/wall-stays') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/wall-stay.png'); ?>" alt="Wall Stays"></a>
										<h3><a href="<?php echo $this->getUrl('products/products/wall-stays') ?>" title="Wall Stays">Wall Stays</a></h3>
									</figcaption>
								</figure>
							</div>
							<div>
								<figure>
									<figcaption>
										<a href="<?php echo $this->getUrl('products/products/accessories') ?>"><img src="<?php echo $this->getSkinUrl('images/hp_categories/accessories.png'); ?>" alt="Accessories"></a>
										<h3><a href="<?php echo $this->getUrl('products/products/accessories') ?>" title="Accessories">Accessories</a></h3>
									</figcaption>
								</figure>
							</div>
						</div>
					</div>
				</div>
				<!-- <div class="row">
					<div class="col-md-12 col-sm-12">
						<div class="divider"></div>
					</div>
					<div class="col-md-6 col-md-offset-3 col-sm-12">
						<a class="twitter-timeline" href="https://twitter.com/Radrestore1" data-widget-id="594848136671186944" data-chrome="nofooter noborders noscrollbar transparent">>Tweets by @Radrestore1</a>
						<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
					</div>
				</div> -->

				<!-- Tweets
				<div class="row">
					<div class="col-md-12 col-sm-12">
						<?php //echo $this->getChildHtml('tweets.tweets') ?>
					</div>
				</div>
				-->
			</div>
		</div>
	</div>

	<?php echo $this->getChildHtml('footer'); ?>

	<?php echo $this->getChildHtml('site.bottom.css.js'); ?>
	<?php echo $this->getChildHtml('before_body_end'); ?>
	<?php echo $this->getAbsoluteFooter(); ?>
</body>
</html>
