<div>
	<label for="">
		Number of sections
		<input type="number" step="1" min="3" max="30">
	</label>
</div>

<div>
	<?php
		$collection = Mage::getModel('catalog/product')->getCollection();
		// $collection->addAttributeToFilter('item_type', 'Finish');
		// var_dump($finishes);
		foreach ($collection as $item) {
			Mage::Log('product found:'.$item->getName());
			// echo $item->getName()."<br/>";
			// echo $finish = Mage::getModel('catalog/product')->loadByAttribute('item_type','Finish');
			// echo "<option value=".$finish->getPrice().">".$finish->getName()."</option>";
		}
	?>
	<label for="">
		Finish
		<select name="" id="">
			<option value="false" selected="selcted" disabled="disabled">Choose finish</option>
		</select>
	</label>
</div>